name: Compiling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Compile on all supported OSes
  compile:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Compile
        run: make compile-only
